Class {
	#name : #SRT07d6c9b63dc0af6bdb32e924fc4e1a689391d230,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT07d6c9b63dc0af6bdb32e924fc4e1a689391d230 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTc7Cgpjb250cmFjdCBHZXRzQnVybmVkIHsKCiAgICBmdW5jdGlvbiAoKSBwYXlhYmxlIHsKICAgIH0KCiAgICBmdW5jdGlvbiBCdXJuTWUgKCkgewogICAgICAgIC8vIFNlbGZkZXN0cnVjdCBhbmQgc2VuZCBldGggdG8gc2VsZiwgCiAgICAgICAgc2VsZmRlc3RydWN0KGFkZHJlc3ModGhpcykpOwogICAgfQp9'.
	

]
