Class {
	#name : #SRT03ab37e5754f55c965101ba1623b3bc91e819b28,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT03ab37e5754f55c965101ba1623b3bc91e819b28 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKY29udHJhY3QgVGVzdENvbnRyYWN0IHsKICAgIHN0cmluZyBuYW1lOwogICAgZnVuY3Rpb24gZ2V0TmFtZSgpIHB1YmxpYyBjb25zdGFudCByZXR1cm5zIChzdHJpbmcpewogICAgICAgIHJldHVybiBuYW1lOwogICAgfQogICAgZnVuY3Rpb24gc2V0TmFtZShzdHJpbmcgbmV3TmFtZSkgcHVibGljIHsKICAgICAgICBuYW1lID0gbmV3TmFtZTsKICAgIH0KfQ=='.
	

]
