Class {
	#name : #SRT1536f307ff0a68e1356507ddccdfa2922a7ff48d,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT1536f307ff0a68e1356507ddccdfa2922a7ff48d >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTE7Cgpjb250cmFjdCBJX1doaXRlTGlzdCB7CiAgICBmdW5jdGlvbiBjb250YWlucyhhZGRyZXNzKSBwdWJsaWMgcmV0dXJucyhib29sKTsKfQoKY29udHJhY3QgV2hpdGVMaXN0VXNlciB7CgogICAgZnVuY3Rpb24gYXNzZXJ0KElfV2hpdGVMaXN0IHdoaXRlTGlzdCwgYWRkcmVzcyBhZGRyKSBleHRlcm5hbCB7CiAgICAgIGFzc2VydCAod2hpdGVMaXN0LmNvbnRhaW5zKGFkZHIpKTsKICAgIH0KCn0='.
	

]
