Class {
	#name : #SRT129a52385d55eff5f9b0c1192586f03359560e3f,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT129a52385d55eff5f9b0c1192586f03359560e3f >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTM7CiAKY29udHJhY3QgSGVsbG9Xb3JsZCB7CiAgICAKICAgIGZ1bmN0aW9uIGdldERhdGEoKSBjb25zdGFudCByZXR1cm5zIChzdHJpbmcpIHsKICAgICAgICByZXR1cm4gIkhlbGxvLCB3b3JsZCEiOwogICAgfQogICAgCn0='.
	

]
