Class {
	#name : #SRT151cfc485ec5a9f45e7bd0983b54ee6504261b32,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT151cfc485ec5a9f45e7bd0983b54ee6504261b32 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMjA7CgovKgoqIFNpbXBseSByZXR1cm5zIGtlY2NhazI1NiBvZiB5b3VyIGV0aCBhZGRyZXNzCiovCgpjb250cmFjdCBrZWt0ZXN0IHsKICAKICAKICAKICBmdW5jdGlvbiBrZWsoYWRkcmVzcykgcHVibGljIHZpZXcgcmV0dXJucyhieXRlczMyKSB7CiAgICAgIAogICAgICBhZGRyZXNzIF9ldGhhZGR5ID0gbXNnLnNlbmRlcjsKICAgICAgICByZXR1cm4gKGtlY2NhazI1NihfZXRoYWRkeSkpOwogIH0gIAogICAgCn0='.
	

]
