Class {
	#name : #SRT1622aafed9a6f0b59ef50a778bcb0cdbf990bf81,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT1622aafed9a6f0b59ef50a778bcb0cdbf990bf81 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTk7Cgpjb250cmFjdCBGb28KewogICAgc3RyaW5nIHB1YmxpYyBwaHJhc2U7CiAgICAKICAgIGZ1bmN0aW9uIEZvbyhzdHJpbmcgX3BocmFzZSkgcHVibGljIHsKICAgICAgICBwaHJhc2UgPSBfcGhyYXNlOwogICAgfQp9'.
	

]
