Class {
	#name : #SRT2bb2f9183e246fc4c157a791c09772016309cd34,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT2bb2f9183e246fc4c157a791c09772016309cd34 >> base64 [
	^ 'Y29udHJhY3QgWmh0b25nIHsKICAgIGFkZHJlc3MgcHVibGljIG93bmVyOwogICAgICB1aW50IHByaXZhdGUgcmVzdWx0OwogICAgICBmdW5jdGlvbiBTZXQoKXsKICAgICAgICAgIG93bmVyID0gbXNnLnNlbmRlcjsKICAgICAgfQogICAgICBmdW5jdGlvbiBhc3NpZ24odWludCB4LCB1aW50IHkpIHJldHVybnMgKHVpbnQpewogICAgICAgICAgcmVzdWx0ID0geCArIHk7CiAgICAgIH0KfQ=='.
	

]
