Class {
	#name : #SRT2f976a5382c0c6214b3d8fe6bdc5379edd35d9d4,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT2f976a5382c0c6214b3d8fe6bdc5379edd35d9d4 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKY29udHJhY3QgR2V0c0J1cm5lZCB7CiAgICBmdW5jdGlvbiAoKSBwYXlhYmxlIHB1YmxpYyB7CiAgICB9CgogICAgZnVuY3Rpb24gQnVybk1lKCkgcHVibGljIHsKICAgICAgICAvLyBTZWxmZGVzdHJ1Y3QgYW5kIHNlbmQgZXRoIHRvIHNlbGYsIAogICAgICAgIHNlbGZkZXN0cnVjdChhZGRyZXNzKHRoaXMpKTsKICAgIH0KfQ=='.
	

]
