Class {
	#name : #SRT258f4a2b9318849a92bff86dbf8dad166617ec96,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT258f4a2b9318849a92bff86dbf8dad166617ec96 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKCmNvbnRyYWN0IEV2ZW50ZXIgewogIGV2ZW50IFJlY29yZCgKICAgIGFkZHJlc3MgX2Zyb20sCiAgICBzdHJpbmcgX21lc3NhZ2UKICApOwoKICBmdW5jdGlvbiByZWNvcmQoc3RyaW5nIG1lc3NhZ2UpIHsKICAgIFJlY29yZChtc2cuc2VuZGVyLCBtZXNzYWdlKTsKICB9Cn0='.
	

]
