Class {
	#name : #SRT3760607b757efebeedacf6692a2db110680188ad,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT3760607b757efebeedacf6692a2db110680188ad >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTE7Cgpjb250cmFjdCBNeUNvbnRyYWN0IHsKICBzdHJpbmcgd29yZCA9ICJBbGwgbWVuIGFyZSBjcmVhdGVkIGVxdWFsISI7CgogIGZ1bmN0aW9uIGdldFdvcmQoKSByZXR1cm5zIChzdHJpbmcpewogICAgcmV0dXJuIHdvcmQ7CiAgfQoKfQ=='.
	

]
