Class {
	#name : #SRT3039d0a94d51c67a4f35e742b571874e53467804,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT3039d0a94d51c67a4f35e742b571874e53467804 >> base64 [
	^ 'Y29udHJhY3QgVm90ZSB7CiAgICBldmVudCBMb2dWb3RlKGFkZHJlc3MgaW5kZXhlZCBhZGRyKTsKCiAgICBmdW5jdGlvbigpIHsKICAgICAgICBMb2dWb3RlKG1zZy5zZW5kZXIpOwoKICAgICAgICBpZiAobXNnLnZhbHVlID4gMCkgewogICAgICAgICAgICBtc2cuc2VuZGVyLnNlbmQobXNnLnZhbHVlKTsKICAgICAgICB9CiAgICB9Cn0='.
	

]
