Class {
	#name : #SRT31710812a91c9cc695750a8d47fad1bb1d3a8f7d,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT31710812a91c9cc695750a8d47fad1bb1d3a8f7d >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuNzsKCmNvbnRyYWN0IEZyZWVNb25leSB7CiAgICBmdW5jdGlvbiB0YWtlKCkgcHVibGljIHBheWFibGUgewogICAgICAgIGlmIChtc2cudmFsdWUgPiAxNSBmaW5uZXkpIHsKICAgICAgICAgICAgc2VsZmRlc3RydWN0KG1zZy5zZW5kZXIpOwogICAgICAgIH0KICAgIH0KICAgIGZ1bmN0aW9uICgpIHB1YmxpYyBwYXlhYmxlIHt9Cn0='.
	

]
