Class {
	#name : #SRT48b4cb193b587c6f2dab1a9123a7bd5e7d490ced,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT48b4cb193b587c6f2dab1a9123a7bd5e7d490ced >> base64 [
	^ 'Y29udHJhY3QgU2ltcGxlU3RvcmFnZSB7CiAgdWludCBzdG9yZWREYXRhOwoKICBmdW5jdGlvbiBzZXQodWludCB4KSB7CiAgICBzdG9yZWREYXRhID0geDsKICB9CgogIGZ1bmN0aW9uIGdldCgpIGNvbnN0YW50IHJldHVybnMgKHVpbnQgcmV0VmFsKSB7CiAgICByZXR1cm4gc3RvcmVkRGF0YTsKICB9Cn0='.
	

]
