Class {
	#name : #SRT41fafb65b1514ce1177287a567002f8978d98205,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT41fafb65b1514ce1177287a567002f8978d98205 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTE7Cgpjb250cmFjdCBNaW5lcmV1bVRva2VuQ3JlYXRpb25TZXJ2aWNlIHsKICAgIC8qIENvbnN0cnVjdG9yICovCiAgICBmdW5jdGlvbiBNaW5lcmV1bVRva2VuQ3JlYXRpb25TZXJ2aWNlKCkgewoKICAgIH0KfQ=='.
	

]
