Class {
	#name : #SRT509F5Ca1C64F0F0A63E5C28aDB3398a3c3ec13cf,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT509F5Ca1C64F0F0A63E5C28aDB3398a3c3ec13cf >> base64 [
	^ 'Y29udHJhY3QgVHJhZGVtYXJrIHsKZnVuY3Rpb24gZ2V0VHJhZGVtYXJrKCkgY29uc3RhbnQgcmV0dXJucyAoc3RyaW5nKSB7CnJldHVybiAiR2xvYmFsIE5ldCBFbmNyeXB0aW9uIEludmVzdG1lbnQgU2VjdXJpdHkgU2VydmljZSAoR05FSVNTKSBTb2Z0d2FyZSI7Cn0KfQ=='.
	

]
