Class {
	#name : #SRT55930261bfebdbe7acfd58e0ebb05a18a733f27f,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT55930261bfebdbe7acfd58e0ebb05a18a733f27f >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTk7Cgpjb250cmFjdCBQdXJlTG9vcAp7CiAgICBmdW5jdGlvbiBleGVjdXRlKCkgcHVibGljIHB1cmUgcmV0dXJucyAodWludCBvdXRwdXQpIHsKICAgICAgICB1aW50IG51bTsKICAgICAgICB3aGlsZSh0cnVlKSB7CiAgICAgICAgICAgIG51bSsrOwogICAgICAgIH0KICAgICAgICByZXR1cm4gbnVtOwogICAgfQp9'.
	

]
