Class {
	#name : #SRT5485c751c582eaf9e8d0ec47d754ee66a2e6e9eb,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT5485c751c582eaf9e8d0ec47d754ee66a2e6e9eb >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKY29udHJhY3QgVGVzdCB7CgogICAgZnVuY3Rpb24gc2VuZChhZGRyZXNzIHRvKSBwdWJsaWN7CiAgICAgICAgaWYgKHRvLmNhbGwoIjB4YWJjZGVmIikpIHsKICAgICAgICAgICAgcmV0dXJuOwogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIHJldmVydCgpOwogICAgICAgIH0KICAgIH0KfQ=='.
	

]
