Class {
	#name : #SRT56ef98199fb28abdccd3b408885ce7168c9fa9fe,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT56ef98199fb28abdccd3b408885ce7168c9fa9fe >> base64 [
	^ 'Ly8gVGVzdCBjb250cmFjdApjb250cmFjdCBUZXN0IHsKICAgIC8vIExldCdzIGJlIG5pY2UgYW5kIGNsZWFuIHVwIGFmdGVyIG91cnNlbHZlcwogICAgZnVuY3Rpb24gZGllKCkgewogICAgICAgIHN1aWNpZGUoMCk7CiAgICB9Cn0='.
	

]
