Class {
	#name : #SRT6a92b2804EaeF97f222d003C94F683333e330693,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT6a92b2804EaeF97f222d003C94F683333e330693 >> base64 [
	^ 'Y29udHJhY3QgdHdvIHsKICAgIAogICAgYWRkcmVzcyBwdWJsaWMgZGVwbG95ZXI7CiAgICAKICAgIAogICAgZnVuY3Rpb24gdHdvKCkgewogICAgICAgIGRlcGxveWVyID0gbXNnLnNlbmRlcjsKICAgIH0KICAgIAogICAgCiAgICBmdW5jdGlvbiBwYXkoKSB7CiAgICAgICAgZGVwbG95ZXIuc2VuZCh0aGlzLmJhbGFuY2UpOwogICAgfQogICAgCiAgICAKICAgIGZ1bmN0aW9uKCkgewogICAgICAgIHBheSgpOwogICAgfQogICAgCiAgICAKfQ=='.
	

]
