Class {
	#name : #SRT6918bf274c2417b866a87c7659dfa91acebd51f4,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT6918bf274c2417b866a87c7659dfa91acebd51f4 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTc7Cgpjb250cmFjdCBTaW1wbGVUZXN0CnsKICAgIHN0cmluZyBwdWJsaWMgYmxhYmxhYmxhOwogICAgZnVuY3Rpb24gU2ltcGxlVGVzdCgpIHB1YmxpYwogICAgewogICAgICAgIGJsYWJsYWJsYSA9ICJIZWxsbyB3b3JsZCEiOwogICAgfQp9'.
	

]
