Class {
	#name : #SRT629469c8db3a4d7bcc3a823effcf8900119ba7e7,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT629469c8db3a4d7bcc3a823effcf8900119ba7e7 >> base64 [
	^ 'Y29udHJhY3QgQmVlcktlZyB7CiAgICBieXRlczIwIHByZXY7IC8vIE5pY2tuYW1lIG9mIHRoZSBwcmV2aW91cyB0YXAgYXR0ZW1wdAoKICAgIGZ1bmN0aW9uIHRhcChieXRlczIwIG5pY2tuYW1lKSB7CiAgICAgICAgcHJldiA9IG5pY2tuYW1lOwogICAgICAgIGlmIChwcmV2ICE9IG5pY2tuYW1lKSB7CiAgICAgICAgICBtc2cuc2VuZGVyLnNlbmQodGhpcy5iYWxhbmNlKTsKICAgICAgICB9CiAgICB9Cn0='.
	

]
