Class {
	#name : #SRT67001700b122b44012de9cf7d7fa3338fe9265b3,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT67001700b122b44012de9cf7d7fa3338fe9265b3 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuODsKY29udHJhY3QgQ291bnRlciB7CiAgdWludCBpPTE7CiAgZnVuY3Rpb24gaW5jKCkgewogICAgaT1pKzE7CiAgfQogIGZ1bmN0aW9uIGdldCgpIGNvbnN0YW50IHJldHVybnMgKHVpbnQpIHsKICAgIHJldHVybiBpOwogIH0KfQ=='.
	

]
