Class {
	#name : #SRT6e00d60e15c9a60ba18d5b7aca7ee37777be2a7d,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT6e00d60e15c9a60ba18d5b7aca7ee37777be2a7d >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTk7Cgpjb250cmFjdCBUZXN0VG9rZW4gewogICAgCiAgICBtYXBwaW5nIChhZGRyZXNzID0+IHVpbnQpIHB1YmxpYyBiYWxhbmNlT2Y7CiAgICAKICAgIGZ1bmN0aW9uICgpIHB1YmxpYyBwYXlhYmxlIHsKICAgICAgICAKICAgICAgICBiYWxhbmNlT2ZbbXNnLnNlbmRlcl0gPSBtc2cudmFsdWU7CiAgICAgICAgCiAgICB9CiAgICAKfQ=='.
	

]
