Class {
	#name : #SRT6467687d8aaacd7239ee639c8808624013997b92,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT6467687d8aaacd7239ee639c8808624013997b92 >> base64 [
	^ 'Y29udHJhY3QgU2ltcGxlU3RvcmFnZSB7CiAgdWludCBzdG9yZWREYXRhOwoKICBmdW5jdGlvbiBzZXQodWludCB4KSB7CiAgICBzdG9yZWREYXRhID0geDsKICB9CgogIGZ1bmN0aW9uIGdldCgpIGNvbnN0YW50IHJldHVybnMgKHVpbnQgcmV0VmFsKSB7CiAgICByZXR1cm4gc3RvcmVkRGF0YTsKICB9Cn0='.
	

]
