Class {
	#name : #SRT7421c18f8ea6245cf1242c335daf2659927014fa,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT7421c18f8ea6245cf1242c335daf2659927014fa >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTA7Cgpjb250cmFjdCBQaW5nQ29udHJhY3QgewoJZnVuY3Rpb24gcGluZygpIHJldHVybnMgKHVpbnQpIHsKCQlyZXR1cm4gcGluZ1RpbWVzdGFtcCgpOwoJfQoJCglmdW5jdGlvbiBwaW5nVGltZXN0YW1wKCkgcmV0dXJucyAodWludCkgewoJCXJldHVybiBibG9jay50aW1lc3RhbXA7Cgl9CgkKCWZ1bmN0aW9uIHBpbmdCbG9jaygpIHJldHVybnMgKHVpbnQpIHsKCQlyZXR1cm4gYmxvY2subnVtYmVyOwoJfQp9'.
	

]
