Class {
	#name : #SRT7e96a18d7aeec64c9c99ed388ff3907d156030de,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT7e96a18d7aeec64c9c99ed388ff3907d156030de >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMjsKCmNvbnRyYWN0IFNoaXRwb3N0IAp7CglzdHJpbmcgY29uc3RhbnQgcHVibGljIHBvc3RlciA9ICJQZWVudXR0QnV0bGVyIjsKCXN0cmluZyBjb25zdGFudCBwdWJsaWMgbWVzc2FnZSA9ICJPbiAyMDE3LzQvMjEsIEkgc2hpdHBvc3RlZCBvbiB0aGUgRXRoZXJldW0gYmxvY2tjaGFpbi4iOwp9'.
	

]
