Class {
	#name : #SRT71caff5fd6facbaf1863426ac05b3703636a9bb9,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT71caff5fd6facbaf1863426ac05b3703636a9bb9 >> base64 [
	^ 'Y29udHJhY3QgVm90ZSB7CiAgICBldmVudCBMb2dWb3RlKGFkZHJlc3MgaW5kZXhlZCBhZGRyKTsKCiAgICBmdW5jdGlvbigpIHsKICAgICAgICBMb2dWb3RlKG1zZy5zZW5kZXIpOwoKICAgICAgICBpZiAobXNnLnZhbHVlID4gMCkgewogICAgICAgICAgICBpZiAoIW1zZy5zZW5kZXIuc2VuZChtc2cudmFsdWUpKSB7CiAgICAgICAgICAgICAgICB0aHJvdzsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KfQ=='.
	

]
