Class {
	#name : #SRT7c99b8f798fd6930e798198da8cfdb76582148de,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT7c99b8f798fd6930e798198da8cfdb76582148de >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTA7CgoKCgoKCmNvbnRyYWN0IEhlbGxvV29ybGQgewoKICBmdW5jdGlvbiBzYXlIZWxsbygpIHB1YmxpYyBjb25zdGFudCByZXR1cm5zIChzdHJpbmcpIHsKICAgIHJldHVybiAiSGVsbG8sIHdvcmxkISEhIjsKICB9CiAgCn0='.
	

]
