Class {
	#name : #SRT85f1b0178c5c0710aa9da3c4409c731aae0a944a,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT85f1b0178c5c0710aa9da3c4409c731aae0a944a >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTg7CgovLyBUaGlzIGlzIHRoZSBIU1QgdG9rZW4gcHVyZ2F0b3J5LCB3aGVyZSBIb3Jpem9uIFN0YXRlCi8vIFRyYW5zZmVycnMgdG9rZW5zIHRoYXQgYXJlIGxvY2tlZCBmb3JldmVyLgpjb250cmFjdCBIU1RQdXJnYXRvcnkgewogICAgCiAgICBmdW5jdGlvbigpIHB1YmxpYyBwYXlhYmxlIHsKICAgICAgICByZXZlcnQoKTsKICAgIH0KCn0='.
	

]
