Class {
	#name : #SRT8c1a31a6e954f989a06fcee1067d426d70891ce9,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT8c1a31a6e954f989a06fcee1067d426d70891ce9 >> base64 [
	^ 'Y29udHJhY3QgU21hcnRWZXJpZnlpbmd7CiAgICBmdW5jdGlvbiBTbWFydFZlcmlmeWluZygpewoKICAgIH0KCiAgICBmdW5jdGlvbigpIHBheWFibGUKICAgIHsKICAgICAgICBpZihtc2cuc2VuZGVyLnNlbmQobXNnLnZhbHVlKT09ZmFsc2UpIHRocm93OwogICAgfQp9'.
	

]
