Class {
	#name : #SRT8154ae317a767e69d7f427aebdfbdddadcd5cf48,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT8154ae317a767e69d7f427aebdfbdddadcd5cf48 >> base64 [
	^ 'Y29udHJhY3QgUmF0aW5nIHsKICAgICAgICBmdW5jdGlvbiBzZXRSYXRpbmcoYnl0ZXMzMiBfa2V5LCB1aW50MjU2IF92YWx1ZSkgewogICAgICAgICAgICByYXRpbmdzW19rZXldID0gX3ZhbHVlOwogICAgICAgIH0KICAgICAgICBtYXBwaW5nIChieXRlczMyID0+IHVpbnQyNTYpIHB1YmxpYyByYXRpbmdzOwogICAgfQ=='.
	

]
