Class {
	#name : #SRT989d5889c93ABd6789aD8B4810060A255cb9a96A,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT989d5889c93ABd6789aD8B4810060A255cb9a96A >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuODsKCmNvbnRyYWN0IGYgewogICAgZnVuY3Rpb24gYSgpIGNvbnN0YW50IHJldHVybnMgKHN0cmluZyBiKXsKICAgICAgICByZXR1cm4gInRpY2tsZXRpY2tsZSB2YWMgYmFuIGluIGNzZ28gbWFyY2ggMTAgMjAxNyI7CiAgICB9Cn0='.
	

]
