Class {
	#name : #SRT9604f4d13f95f7db2479b05eb60bac3bf2cd345b,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT9604f4d13f95f7db2479b05eb60bac3bf2cd345b >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTM7CmNvbnRyYWN0IEhlbGxvV29ybGQgewogICAgCiAgICBmdW5jdGlvbiBnZXREYXRhKCkgcHVibGljIGNvbnN0YW50IHJldHVybnMgKHN0cmluZykgewogICAgICAgIHJldHVybiAiSGVsbG8sIHdvcmxkISI7CiAgICB9CiAgIAp9'.
	

]
