Class {
	#name : #SRT9295ede03f6eab5c8f215d3ddcf7dca3a26ca087,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT9295ede03f6eab5c8f215d3ddcf7dca3a26ca087 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKCmNvbnRyYWN0IFNpbXBsZVN0b3JhZ2UgewogICAgdWludCBzdG9yZWREYXRhOwoKICAgIGZ1bmN0aW9uIHNldCh1aW50IHgpIHsKICAgICAgICBzdG9yZWREYXRhID0geDsKICAgIH0KCiAgICBmdW5jdGlvbiBnZXQoKSBjb25zdGFudCByZXR1cm5zICh1aW50IHN0b3JlZERhdGEpIHsKICAgICAgICByZXR1cm4gc3RvcmVkRGF0YTsKICAgIH0KfQ=='.
	

]
