Class {
	#name : #SRT91583c4cca21ee968adee187bdb94186da992b73,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRT91583c4cca21ee968adee187bdb94186da992b73 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKCmNvbnRyYWN0IFRlc3RSZXZlcnQgewogICAgZnVuY3Rpb24gdGVzdF9yZXF1aXJlKCkgcHVibGljIHsKICAgICAgICByZXF1aXJlKG5vdyA8IDEwMDApOwogICAgfQoKICAgIGZ1bmN0aW9uIHRlc3RfYXNzZXJ0KCkgcHVibGljIHsKICAgICAgICBhc3NlcnQobm93IDwgMTAwMCk7CiAgICB9Cn0='.
	

]
