Class {
	#name : #SRTa90f15a8323ac98a80629e229ba47f944dfca658,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTa90f15a8323ac98a80629e229ba47f944dfca658 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTg7Cgpjb250cmFjdCBQYXpodWtvdk1heEluRVRIIHsKICAgIAogICAgYnl0ZXMzMiBpbmZvID0gIkknbSBzbWFydCBjb250cmFjdCBmcm9tIHA1bS5ydSEiOwogICAgCiAgICBmdW5jdGlvbiBnZXRJbmZvKCkgdmlldyBwdWJsaWMgcmV0dXJucyAoYnl0ZXMzMikgewogICAgICAgIHJldHVybiAoaW5mbyk7CiAgICB9CiAgICAKfQ=='.
	

]
