Class {
	#name : #SRTa213997612e2b0919c3144e657ac0926c447c134,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTa213997612e2b0919c3144e657ac0926c447c134 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuNjsKCmNvbnRyYWN0IE1vb25Cb29rIHsgCiAgZnVuY3Rpb24gTW9vbkJvb2soKSB7fQoKICBieXRlc1tdIHRlcm1zOwoKICBmdW5jdGlvbiBwdXQoYnl0ZXMgdGVybSkgewogICAgdGVybXMucHVzaCh0ZXJtKTsKICB9CgogIGZ1bmN0aW9uIGdldCh1aW50MjU2IGluZGV4KSBjb25zdGFudCByZXR1cm5zIChieXRlcykgewogICAgcmV0dXJuIHRlcm1zW2luZGV4XTsKICB9Cn0='.
	

]
