Class {
	#name : #SRTb19c9e527fe2476cB26d7B92624b6fe806b70Ae1,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTb19c9e527fe2476cB26d7B92624b6fe806b70Ae1 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTk7CmNvbnRyYWN0IFpaX01hbmR5CnsKICAgIGZ1bmN0aW9uIGdldE1lc3NhZ2UoKSBwdWJsaWMgcHVyZSByZXR1cm5zIChieXRlczMyKSB7CiAgICAgICAgcmV0dXJuICJaWiBsb3ZlcyBtYW5keS4iOwogICAgfQp9'.
	

]
