Class {
	#name : #SRTb5194ff3f7d7a352c4cfb085e3fe16ae70243f3a,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTb5194ff3f7d7a352c4cfb085e3fe16ae70243f3a >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMjA7Cgpjb250cmFjdCBNaWtleUxvdmVzTXVsbHkgCnsKCXN0cmluZyBjb25zdGFudCBwdWJsaWMgcG9zdGVyID0gIk1pY2hhZWwiOwoJc3RyaW5nIGNvbnN0YW50IHB1YmxpYyBtZXNzYWdlID0gIkhhcHB5IGFubml2ZXJzYXJ5IE11bGx5ISBJIGxvdmUgeW91IGZvcmV2ZXIuIjsKfQ=='.
	

]
