Class {
	#name : #SRTb6346ce38af410a9dae2e827ba21c413aee36658,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTb6346ce38af410a9dae2e827ba21c413aee36658 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTk7Cgpjb250cmFjdCBQdXJlTG9vcAp7CiAgICBmdW5jdGlvbiBleGVjdXRlKCkgcHVibGljIHB1cmUgcmV0dXJucyAodWludCBvdXRwdXQpIHsKICAgICAgICB1aW50IG51bTsKICAgICAgICBudW0gKz1leGVjdXRlKCk7CiAgICAgICAgcmV0dXJuIG51bSsrOwogICAgfQp9'.
	

]
