Class {
	#name : #SRTbf614eaf32e40581455242579b8e20d03551212f,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTbf614eaf32e40581455242579b8e20d03551212f >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTE7Cgpjb250cmFjdCBDb2luYmFzZUZ1bmRzRm9yd2FyZGluZwp7CglhZGRyZXNzIHB1YmxpYyBjb2luYmFzZVdhbGxldCA9IDB4OTE5QzgxMmYxYTBmMmVBNWEyYzg3MjRDOTEwZUMwQjYxRjAyMEZmMDsKCglmdW5jdGlvbiAoKSBwYXlhYmxlIHsKCQljb2luYmFzZVdhbGxldC50cmFuc2Zlcihtc2cudmFsdWUpOwoJfQp9'.
	

]
