Class {
	#name : #SRTbe16ba60960a5e92bc878814dddc736252db8f32,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTbe16ba60960a5e92bc878814dddc736252db8f32 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTM7Cgpjb250cmFjdCBEYXBwVHV0b3JpYWwgewogIHVpbnQgc3RvcmVkRGF0YTsKCiAgZnVuY3Rpb24gc2V0KHVpbnQgeCkgewogICAgc3RvcmVkRGF0YSA9IHg7CiAgfQoKICBmdW5jdGlvbiBnZXQoKSBjb25zdGFudCByZXR1cm5zICh1aW50KSB7CiAgICByZXR1cm4gc3RvcmVkRGF0YSAqIDI7CiAgfQp9'.
	

]
