Class {
	#name : #SRTc6b13d41866cba306fe9ddfafd580ac8d92bfb75,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTc6b13d41866cba306fe9ddfafd580ac8d92bfb75 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuNDsgLy8gb3B0aW1pemF0aW9uIGVuYWJsZWQKCmNvbnRyYWN0IFNlbmRCYWNrIHsKICAgIGZ1bmN0aW9uKCkgcGF5YWJsZSB7CiAgICAgICAgaWYgKCFtc2cuc2VuZGVyLnNlbmQobXNnLnZhbHVlKSkKICAgICAgICAgICAgdGhyb3c7CiAgICB9Cn0='.
	

]
