Class {
	#name : #SRTce5093dd7cf90699bba881af8f2c8ad0a7066dc5,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTce5093dd7cf90699bba881af8f2c8ad0a7066dc5 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTg7CiAgICAgIApjb250cmFjdCBNdWx0aVRyYW5zZmVyIHsKICAgIGZ1bmN0aW9uIG11bHRpVHJhbnNmZXIoYWRkcmVzcyB0b2tlbiwgYWRkcmVzc1tdIF9hZGRyZXNzZXMsIHVpbnQyNTYgYW1vdW50KSBwdWJsaWMgewogICAgICAgIGZvciAodWludDI1NiBpID0gMDsgaSA8IF9hZGRyZXNzZXMubGVuZ3RoOyBpKyspIHsKICAgICAgICAgICAgdG9rZW4udHJhbnNmZXIoYW1vdW50KTsKICAgICAgICB9CiAgICB9Cn0='.
	

]
