Class {
	#name : #SRTc333b0bc21A64A56aB7e59D77b486D4Ee41a50A2,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTc333b0bc21A64A56aB7e59D77b486D4Ee41a50A2 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTY7Cgpjb250cmFjdCBBS1ZhbHVlVGVzdAp7CiAgICB1aW50MjU2IHB1YmxpYyBzb21lVmFsdWU7CiAgICAKICAgIGZ1bmN0aW9uIHNldFNvbWVWYWx1ZSh1aW50MjU2IG5ld1ZhbHVlKQogICAgewogICAgICAgIHNvbWVWYWx1ZSA9IG5ld1ZhbHVlOwogICAgfQp9'.
	

]
