Class {
	#name : #SRTce1555c4fc4ddc2d87183d1a36e0a410e565624d,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTce1555c4fc4ddc2d87183d1a36e0a410e565624d >> base64 [
	^ 'Y29udHJhY3Qgc3RvcmFkZ2UgewogICAgZXZlbnQgbG9nKHN0cmluZyBkZXNjcmlwdGlvbik7CglmdW5jdGlvbiBzYXZlKAogICAgICAgIHN0cmluZyBtZGhhc2gKICAgICkKICAgIHsKICAgICAgICBsb2cobWRoYXNoKTsKICAgIH0KfQ=='.
	

]
