Class {
	#name : #SRTc971af31326977c45a9c31fbc05c5faa45021e19,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTc971af31326977c45a9c31fbc05c5faa45021e19 >> base64 [
	^ 'Y29udHJhY3QgY2hlY2sgewogICAgZnVuY3Rpb24gYWRkKGFkZHJlc3MgX2FkZCwgdWludCBfcmVxKSB7CiAgICAgICAgX2FkZC5jYWxsY29kZShieXRlczQoa2VjY2FrMjU2KCJjaGFuZ2VSZXF1aXJlbWVudCh1aW50MjU2KSIpKSwgX3JlcSk7CiAgICB9Cn0='.
	

]
