Class {
	#name : #SRTc54d1a03e5fc1558d4a95e9fbbb2423f02168c23,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTc54d1a03e5fc1558d4a95e9fbbb2423f02168c23 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMDsKCmNvbnRyYWN0IEhlbGxvV29ybGQgewogICAgCiAgICBmdW5jdGlvbiBncmVldGVyIChieXRlczMyIGlucHV0KSByZXR1cm5zIChieXRlczMyIG91dHB1dCkgewogICAgICAgIHJldHVybiBpbnB1dDsKICAgIH0KCn0='.
	

]
