Class {
	#name : #SRTc02df3e98cbc4416e5471f51ea57ce8845a844cd,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTc02df3e98cbc4416e5471f51ea57ce8845a844cd >> base64 [
	^ 'Y29udHJhY3QgY2FsYyB7IAogICAgZXZlbnQgcmV0KHVpbnQgcik7CiAgICBmdW5jdGlvbiBtdWx0aXBseSh1aW50IGEsIHVpbnQgYikgcmV0dXJucyh1aW50IGQpIHsgCiAgICAgICAgdWludCByZXMgPSBhICogYjsKICAgICAgICByZXQgKHJlcyk7CiAgICAgICAgcmV0dXJuIHJlczsgCiAgICB9IAp9'.
	

]
