Class {
	#name : #SRTD5c93B00516AF744933016179195ACCD3dEd981E,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTD5c93B00516AF744933016179195ACCD3dEd981E >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuODsKCmNvbnRyYWN0IE15Q29udHJhY3QgewogICAgZnVuY3Rpb24gd2hhdERpZEphc29uU2F5KCkgY29uc3RhbnQgcmV0dXJucyAoc3RyaW5nIHNhaWQpewogICAgICAgIHJldHVybiAiZXRoZXIgaXMgYSBzY2FtIjsKICAgIH0KfQ=='.
	

]
