Class {
	#name : #SRTdb22939e20A4C41cd7e2b9B325ce452B36c80dd9,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTdb22939e20A4C41cd7e2b9B325ce452B36c80dd9 >> base64 [
	^ 'Y29udHJhY3QgQWx3YXlzRmFpbCB7CgogICAgZnVuY3Rpb24gQWx3YXlzRmFpbCgpIHsKICAgIH0KICAgIAogICAgZnVuY3Rpb24oKSB7CiAgICAgICAgZW50ZXIoKTsKICAgIH0KICAgIAogICAgZnVuY3Rpb24gZW50ZXIoKSB7CiAgICAgICAgdGhyb3c7CiAgICB9Cn0='.
	

]
