Class {
	#name : #SRTe6069f1c9d78ebc232c1726bf4faa727d83ae31d,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTe6069f1c9d78ebc232c1726bf4faa727d83ae31d >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMjsKCmNvbnRyYWN0IEJyZXR0bWVzc2FnZSAKewoJc3RyaW5nIGNvbnN0YW50IHB1YmxpYyBwb3N0ZXIgPSAiQkpEIjsKCXN0cmluZyBjb25zdGFudCBwdWJsaWMgbWVzc2FnZSA9ICJQb3N0ZWQ6Mi83LzE4IEhlbGxvIVBXSzpXSSI7Cn0='.
	

]
