Class {
	#name : #SRTeb3c1a7f816da958a0f8b9f4ef63a19b26d03739,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTeb3c1a7f816da958a0f8b9f4ef63a19b26d03739 >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMjsKCmNvbnRyYWN0IHN0b3JhZGdlIHsKICAgIAogICAgZXZlbnQgbG9nKHN0cmluZyBkZXNjcmlwdGlvbik7CiAgICAKCWZ1bmN0aW9uIHNhdmUoCiAgICAgICAgc3RyaW5nIG1kaGFzaAogICAgKQogICAgewogICAgICAgIGxvZyhtZGhhc2gpOwogICAgfQp9'.
	

]
