Class {
	#name : #SRTF2289a55cd754D3b586CAc1675E1c157A36637BB,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTF2289a55cd754D3b586CAc1675E1c157A36637BB >> base64 [
	^ 'Y29udHJhY3QgU2ltcGxlU3RvcmFnZSB7CiAgICB1aW50IHN0b3JlZERhdGE7CiAgICBmdW5jdGlvbiBzZXQodWludCB4KSB7CiAgICAgICAgc3RvcmVkRGF0YSA9IHg7CiAgICB9CiAgICBmdW5jdGlvbiBnZXQoKSBjb25zdGFudCByZXR1cm5zICh1aW50IHJldFZhbCkgewogICAgICAgIHJldHVybiBzdG9yZWREYXRhOwogICAgfQp9'.
	

]
