Class {
	#name : #SRTf603c4161c388b77249486f9cb6f1741abda6a9b,
	#superclass : #SRTContracts,
	#category : #SolidityTestingResources
}

{ #category : #base64 }
SRTf603c4161c388b77249486f9cb6f1741abda6a9b >> base64 [
	^ 'cHJhZ21hIHNvbGlkaXR5IF4wLjQuMTU7Cgpjb250cmFjdCBCdXJuZXIgewoKICAgIGZ1bmN0aW9uIHRva2VuRmFsbGJhY2soYWRkcmVzcyAvKiBfZnJvbSAqLywgdWludCAvKiBfdmFsdWUgKi8sIGJ5dGVzIC8qIF9kYXRhICovKSByZXR1cm5zIChib29sIHJlc3VsdCkgewogICAgICAgIHJldHVybiB0cnVlOwogICAgfQoKfQ=='.
	

]
